DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS gift_certificate;
DROP TABLE IF EXISTS tag_has_gift_certificate;
DROP TABLE IF EXISTS user_account;
DROP TABLE IF EXISTS user_order;

CREATE TABLE IF NOT EXISTS tag
(
    ID    BIGINT(100)  NOT NULL AUTO_INCREMENT,
    NAME  VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS gift_certificate
(
    ID                     BIGINT(100)   NOT NULL AUTO_INCREMENT,
    NAME                   VARCHAR(200)  NOT NULL,
    DESCRIPTION            VARCHAR(1000) NOT NULL,
    PRICE                  DECIMAL(7, 2) NOT NULL,
    CREATEDATE             DATETIME      NOT NULL,
    CREATEDATETIMEZONE     VARCHAR(50)   NOT NULL,
    LASTUPDATEDATE         DATETIME      NOT NULL,
    LASTUPDATEDATETIMEZONE VARCHAR(50)   NOT NULL,
    DURATION               INT           NOT NULL,
    USER_ORDER_ID          BIGINT(100)   NOT NULL,
    PRIMARY KEY (ID, USER_ORDER_ID)
);

CREATE TABLE IF NOT EXISTS tag_has_gift_certificate
(
    TAG_ID              BIGINT(100) NOT NULL,
    GIFT_CERTIFICATE_ID BIGINT(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_account
(
    ID       BIGINT(100)  NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(200) NOT NULL,
    EMAIL    VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS user_order
(
    ID                         BIGINT(100)   NOT NULL AUTO_INCREMENT,
    COST                       DECIMAL(9, 2) NOT NULL,
    CREATE_DATE                DATETIME      NOT NULL,
    CREATE_DATE_TIME_ZONE      VARCHAR(50)   NOT NULL,
    LAST_UPDATE_DATE           DATETIME      NOT NULL,
    LAST_UPDATE_DATE_TIME_ZONE VARCHAR(50)   NOT NULL,
    USER_ACCOUNT_ID            BIGINT(100)   NOT NULL,
    PRIMARY KEY (ID, USER_ACCOUNT_ID)
);

